# Generated by Django 4.1.7 on 2025-01-11 15:15

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('position', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('position', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=1)),
                ('photo_page', models.CharField(blank=True, default='', max_length=255)),
                ('extra_text', markdownx.models.MarkdownxField(blank=True, default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fresha.category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('str_id', models.CharField(default='sv', max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('position', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=1)),
                ('price', models.FloatField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('caption', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fresha.group')),
            ],
        ),
    ]
