# Generated by Django 4.2.3 on 2023-07-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fresha', '0004_alter_service_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='id',
            new_name='svid',
        ),
    ]
