# Generated by Django 4.2.3 on 2023-07-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresha', '0005_rename_id_service_svid'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
