# Generated by Django 4.2.3 on 2023-07-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresha', '0006_service_id_alter_service_svid'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='str_id',
            field=models.CharField(default='', max_length=25),
        ),
    ]
