# Generated by Django 4.2.3 on 2023-07-06 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fresha', '0007_remove_service_svid_service_str_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('str_id', models.CharField(default='sv', max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('position', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=1)),
                ('price', models.FloatField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fresha.group')),
            ],
        ),
    ]
