# Generated by Django 4.2.3 on 2023-07-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresha', '0008_item_delete_service'),
    ]

    operations = [
    ]
