# Generated by Django 4.2.3 on 2023-07-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresha', '0009_item_caption_delete_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='photo_page',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
