# Generated by Django 4.2.3 on 2023-12-17 19:07

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('fresha', '0010_group_photo_page_delete_service'),
    ]

    operations = [
    ]
