# Generated by Django 4.1.7 on 2024-12-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_service_serviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceid',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
