# Generated by Django 4.1.7 on 2024-12-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_service_category_name_alter_service_serviceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='serviceid',
        ),
    ]
