# Generated by Django 4.2.3 on 2024-12-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20, unique=True)),
                ('client', models.CharField(max_length=255)),
                ('team_member', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('created_dt', models.DateTimeField()),
                ('scheduled_dt', models.DateTimeField()),
                ('cancelled_dt', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('appt_slot', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=255)),
                ('cancelled_by', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('fees_charged', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cdt', models.DateTimeField(auto_now_add=True, null=True)),
                ('udt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
