# Generated by Django 4.1.7 on 2024-12-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('team_member_id', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('appointments', models.CharField(blank=True, max_length=20, null=True)),
                ('user_permission', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('service_commission', models.CharField(blank=True, max_length=255, null=True)),
                ('product_commission', models.CharField(blank=True, max_length=255, null=True)),
                ('voucher_commission', models.CharField(blank=True, max_length=255, null=True)),
                ('cdt', models.DateTimeField(auto_now_add=True, null=True)),
                ('udt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
