# Generated by Django 4.1.7 on 2024-12-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.IntegerField()),
                ('extra_time', models.CharField(blank=True, max_length=255, null=True)),
                ('tax', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_name', models.CharField(max_length=255)),
                ('treatment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('resource', models.CharField(blank=True, max_length=20, null=True)),
                ('online_booking', models.CharField(blank=True, max_length=20, null=True)),
                ('available_for', models.CharField(blank=True, max_length=20, null=True)),
                ('voucher_sales', models.CharField(blank=True, max_length=20, null=True)),
                ('commissions', models.CharField(blank=True, max_length=20, null=True)),
                ('sku', models.CharField(blank=True, max_length=20, null=True)),
                ('cdt', models.DateTimeField(auto_now_add=True, null=True)),
                ('udt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
