# Generated by Django 4.1.7 on 2024-12-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appt_slot',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cancelled_dt',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='fees_charged',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='location',
        ),
        migrations.AddField(
            model_name='appointment',
            name='scheduled_tm',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_dt',
            field=models.DateField(null=True),
        ),
    ]
