# Generated by Django 4.1.7 on 2024-12-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_appointment_appt_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='channel',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
