# Generated by Django 4.1.7 on 2024-12-26 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_appointment_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='scheduled_dt',
            new_name='scheduled_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='scheduled_tm',
            new_name='scheduled_time',
        ),
    ]
