# Generated by Django 4.1.7 on 2024-12-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_scheduled_dt_appointment_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='deposit_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
