# Generated by Django 4.1.7 on 2025-01-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_client_user_id_alter_client_accepts_marketing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.CharField(max_length=20),
        ),
    ]
