# Generated by Django 4.1.7 on 2025-01-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_service_name_alter_service_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='tax',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
