# Generated by Django 4.1.7 on 2025-01-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_service_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
    ]
