# Generated by Django 4.1.7 on 2023-07-04 12:54

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('blog', models.BooleanField(default=False, verbose_name='Publish to blog')),
                ('blog_start_dt', models.DateTimeField(blank=True, null=True, verbose_name='Published')),
                ('email', models.BooleanField(default=False, verbose_name='Send as newsletter')),
                ('email_subject', models.CharField(blank=True, default='', max_length=100, verbose_name='Subject')),
                ('email_send_dt', models.DateTimeField(blank=True, null=True, verbose_name='Sent')),
                ('email_status', models.IntegerField(choices=[(0, 'None'), (1, 'Sending'), (2, 'Sent')], default=0)),
                ('domain', models.IntegerField(choices=[(1, 'Co Uk'), (2, 'Eu')], default=1)),
                ('title_color', models.CharField(blank=True, default='#232323', max_length=20, verbose_name='Title Color')),
                ('title_bgcolor', models.CharField(blank=True, default='#eeeeee', max_length=20, verbose_name='Title Bg Color')),
                ('text', markdownx.models.MarkdownxField(blank=True, verbose_name='Text')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date/Time')),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date/Time')),
                ('description', models.TextField(blank=True, default='', verbose_name='Meta Description')),
                ('keywords', models.TextField(blank=True, default='', verbose_name='Meta Keywords')),
                ('json_ld', models.TextField(blank=True, default='', verbose_name='script ld+json')),
                ('category', models.ManyToManyField(to='blog.category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
